/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courierservice;
import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import java.text.*;
import java.awt.print.*;
import javafx.print.Printer;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;




/**
 *
 * @author Savindu Nimsara
 */
public class remake2oop extends javax.swing.JFrame {
    
       Connection con;
       PreparedStatement pst;
       ResultSet rs;
    /**
     * Creates new form remake2oop
     */
    public remake2oop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonrecipt = new javax.swing.JButton();
        jButtonprint = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblsendername = new javax.swing.JLabel();
        txtsendername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblsenderaddress = new javax.swing.JLabel();
        txtsenderaddress = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbldeliveryid = new javax.swing.JLabel();
        txtsendercontact = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblsendercontactno = new javax.swing.JLabel();
        txtdeliveryid = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblrecivername = new javax.swing.JLabel();
        txtrecivername = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblreciveraddress = new javax.swing.JLabel();
        txtreciveraddress = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblweight = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblshiippingcharges = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblcost = new javax.swing.JLabel();
        txtshipping = new javax.swing.JTextField();
        lblpaymentstatus = new javax.swing.JLabel();
        txtpaymentmethod = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lbldate = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lblpaymentmethod = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblrecivercontactno = new javax.swing.JLabel();
        txtrecivercontactno = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lblcostlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButtonrecipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonrecipt.setForeground(new java.awt.Color(255, 255, 255));
        jButtonrecipt.setText("RECIEIPT");
        jButtonrecipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonrecipt.setContentAreaFilled(false);
        jButtonrecipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonrecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreciptActionPerformed(evt);
            }
        });

        jButtonprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonprint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonprint.setText("PRINT");
        jButtonprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonprint.setContentAreaFilled(false);
        jButtonprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprintActionPerformed(evt);
            }
        });

        jButtonexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonexit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonexit.setText("BACK TO PROFILE");
        jButtonexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonexit.setContentAreaFilled(false);
        jButtonexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonexit, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jButtonprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonrecipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButtonrecipt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonprint, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblsendername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblsendername.setText("SENDER NAME");

        txtsendername.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 255));

        lblsenderaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblsenderaddress.setText("SENDER ADDRESS");

        txtsenderaddress.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(153, 153, 255));

        lbldeliveryid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldeliveryid.setText("DELIVERY ID");

        txtsendercontact.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(153, 153, 255));

        lblsendercontactno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblsendercontactno.setText("SENDER CONTACT NO");

        txtdeliveryid.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(153, 153, 255));

        lblrecivername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblrecivername.setText("RECIEVER NAME");

        txtrecivername.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(153, 153, 255));

        lblreciveraddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblreciveraddress.setText("RECIEVER ADDRESS");

        txtreciveraddress.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(153, 153, 255));

        lblweight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblweight.setText("WEIGHT(Kg)");

        jSeparator7.setBackground(new java.awt.Color(153, 153, 255));

        lblshiippingcharges.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblshiippingcharges.setText("SHIPPING CHARGES");

        txtweight.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(153, 153, 255));

        lblcost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcost.setText("COST");

        txtshipping.setBorder(null);
        txtshipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtshippingActionPerformed(evt);
            }
        });

        lblpaymentstatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblpaymentstatus.setText("PAYMENT STATUS");

        txtpaymentmethod.setBorder(null);

        jSeparator10.setBackground(new java.awt.Color(153, 153, 255));

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldate.setText("DATE");

        txtpayment.setBorder(null);

        jSeparator11.setBackground(new java.awt.Color(153, 153, 255));

        lblpaymentmethod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblpaymentmethod.setText("PAYMENT METHOD");

        txtdate.setBorder(null);

        jSeparator12.setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1728, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel13.setBackground(new java.awt.Color(153, 153, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("COURIER DELIVERY SYSTEM-DELIVERY");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblrecivercontactno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblrecivercontactno.setText("RECIEVER CONTACT NO");

        txtrecivercontactno.setBorder(null);

        jSeparator13.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblsendercontactno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsendercontact, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblreciveraddress)
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtreciveraddress)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbldate)
                                            .addComponent(lblpaymentstatus)
                                            .addComponent(lblshiippingcharges)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lblrecivercontactno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtrecivercontactno, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblsenderaddress)
                                                    .addComponent(lblsendername)
                                                    .addComponent(lbldeliveryid))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtdeliveryid, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jSeparator1)
                                                        .addComponent(txtsendername)
                                                        .addComponent(txtsenderaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(lblrecivername)
                                                    .addGap(48, 48, 48)
                                                    .addComponent(txtrecivername, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                            .addComponent(lblweight)
                                                            .addGap(24, 24, 24))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                            .addComponent(lblpaymentmethod)
                                                            .addGap(30, 30, 30)))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(lblcost)
                                                        .addGap(107, 107, 107)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator12)
                                                    .addComponent(txtdate)
                                                    .addComponent(jSeparator11)
                                                    .addComponent(jSeparator10)
                                                    .addComponent(jSeparator8)
                                                    .addComponent(jSeparator7)
                                                    .addComponent(txtweight)
                                                    .addComponent(txtshipping)
                                                    .addComponent(txtpaymentmethod, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblcostlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(39, 39, 39)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblsendername)
                                    .addComponent(txtsendername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblsenderaddress)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtsenderaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbldeliveryid)
                                    .addComponent(txtdeliveryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblsendercontactno)
                                    .addComponent(txtsendercontact, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblrecivername)
                                    .addComponent(txtrecivername, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtreciveraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblreciveraddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtrecivercontactno, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblrecivercontactno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblweight)
                                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblshiippingcharges)
                                    .addComponent(txtshipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcost, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcostlbl))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblpaymentstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpaymentmethod, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpaymentmethod, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addComponent(jScrollPane1)))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonreciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreciptActionPerformed
        jTextArea1.setText("");
        
        child_clz cost_of_Items = new child_clz();
        double icost,iSubtotal;


        cost_of_Items.weight=cost_of_Items.pweight*Double.parseDouble(txtweight.getText());
        iSubtotal = cost_of_Items.GetAmount();
        icost=iSubtotal;
 

        String cost = String.format("Rs%.2f", icost);
        lblcostlbl.setText(cost);
    
    
        int refs = 1325 + (int) (Math.random()*4238);
        
           Calendar timer= Calendar.getInstance();
           timer.getTime();
           SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
           tTime.format(timer.getTime());
           SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-YYYY");
           Tdate.format(timer.getTime());
      
      
    	jTextArea1.append("\tCourier Delivery Management Systems\n"+
               
                
                "\n\n Sendetr Name: "+txtsendername.getText()+"\n"+
                "\n Sender address: "+txtsenderaddress.getText()+"\n"+
                "\n Delivery Id: "+txtdeliveryid.getText()+"\n"+ "\n Sender Contact No: "+txtsendercontact.getText()+
                
              
                "\n\n=============================="+"\n\n"+
                           
                " Reciever Name: "+txtrecivername.getText()+"\n"+
                        "\n Reciever Addess: "+txtreciveraddress.getText()+"\n"+
                        "\n Reciever Contact No: "+txtrecivercontactno.getText()+"\n"+
                        "\n Weight: "+txtweight.getText()+"\n"+
                        "\n Shipping Method: "+txtshipping.getText()+"\n"+
                        "\n Cost: "+lblcostlbl.getText()+"\n"+ "\n Payment Status: "+  txtpayment.getText()+"\n"+
                        "\n Payment Method: "+txtpaymentmethod.getText()+"\n"+
                                                                  
                                                         
                        "\n=============================="+
                        "\n Date: " +Tdate.format(timer.getTime())+
                        "\n Time: "+tTime.format(timer.getTime())+"\n"+
                                         
                        " Thank You");
        
        try{
            
            String sql = "INSERT INTO `delivery`"
            +"(`sendername`, `senderaddress`, `deliveryid`, `sendercontactno`, `recivername`, `reciveraddress`, `recivercontactno`, `weight`, `shippingcharges`, `cost`, `paymentstatus`, `paymentmethod`, `date`)" 
            +" VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:1433/news","root",""); 
            
            pst=con.prepareStatement(sql);
            
             
             pst.setString(1,txtsendername.getText());
             pst.setString(2,txtsenderaddress.getText());
             pst.setString(3,txtdeliveryid.getText());
             pst.setString(4,txtsendercontact.getText());
             pst.setString(5,txtrecivername.getText());
             pst.setString(6,txtreciveraddress.getText());
             pst.setString(7,txtrecivercontactno.getText());
             pst.setString(8,txtweight.getText());
             pst.setString(9,txtshipping.getText());
             pst.setString(10,lblcostlbl.getText());
             pst.setString(11,txtpayment.getText());
             pst.setString(12,txtpaymentmethod.getText());
             pst.setString(13,txtdate.getText());
             pst.executeUpdate();
            
             
          
        }catch(HeadlessException | SQLException ex){
            
             JOptionPane.showMessageDialog(null,ex);
        
        }    
    }//GEN-LAST:event_jButtonreciptActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed

        Profile ff = new Profile();
        ff.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprintActionPerformed
 
try{
    jTextArea1.print();
}

catch(java.awt.print.PrinterException e){
    System.err.format("No Printer found",e.getMessage() );
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonprintActionPerformed

    private void txtshippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtshippingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtshippingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remake2oop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remake2oop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remake2oop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remake2oop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remake2oop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonprint;
    private javax.swing.JButton jButtonrecipt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblcost;
    private javax.swing.JLabel lblcostlbl;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldeliveryid;
    private javax.swing.JLabel lblpaymentmethod;
    private javax.swing.JLabel lblpaymentstatus;
    private javax.swing.JLabel lblreciveraddress;
    private javax.swing.JLabel lblrecivercontactno;
    private javax.swing.JLabel lblrecivername;
    private javax.swing.JLabel lblsenderaddress;
    private javax.swing.JLabel lblsendercontactno;
    private javax.swing.JLabel lblsendername;
    private javax.swing.JLabel lblshiippingcharges;
    private javax.swing.JLabel lblweight;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdeliveryid;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JTextField txtpaymentmethod;
    private javax.swing.JTextField txtreciveraddress;
    private javax.swing.JTextField txtrecivercontactno;
    private javax.swing.JTextField txtrecivername;
    private javax.swing.JTextField txtsenderaddress;
    private javax.swing.JTextField txtsendercontact;
    private javax.swing.JTextField txtsendername;
    private javax.swing.JTextField txtshipping;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
